services:
    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~,App\Entity\Category,~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.category.title}
        public: true

    admin.product:
            class: App\Admin\ProductAdmin
            arguments: [~,App\Entity\Product,~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: admin.product.title}
            public: true


    admin.user:
            class: App\Admin\UserAdmin
            arguments: [~,App\Entity\User,~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: admin.user.title}
            public: true


    admin.order:
            class: App\Admin\OrderAdmin
            arguments: [~,App\Entity\Order,~]
            tags:
                - {name: sonata.admin, manager_type: orm, label: admin.order.title}
            calls:
                - [setTemplate,['outer_list_rows_list','admin/order/row.html.twig']]
            public: true

    admin.order_item:
                class: App\Admin\OrderItemAdmin
                arguments: [~,App\Entity\OrderItem,~]
                tags:
                    - {name: sonata.admin, manager_type: orm, label: admin.order_item.title, show_in_dashboard: false}
                public: true