vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /image/products
           upload_destination: '%kernel.project_dir%/public/image/products'
           namer: vich_uploader.namer_uniqid
           directory_namer: vich_uploader.directory_namer_subdir
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
